# backend/cloudbuild.yaml
steps:
# 1. Build the Docker image and push to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-and-push-backend' # Assign an ID to this step
  # Use $_BUILD_ID for a reliable unique tag
  args: ['build', '-t', 'gcr.io/gen-lang-client-0960260048/todo-backend:$_BUILD_ID', '.']
  dir: '.' # Ensure context is the backend directory

# 2. Deploy the new image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'todo-backend'
  - '--image'
  - 'gcr.io/gen-lang-client-0960260048/todo-backend:$_BUILD_ID' # Use $_BUILD_ID for deployment
  - '--region'
  - 'us-central1' # Your specified region
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  # The backend does not need REACT_APP_BACKEND_URL
  waitFor: ['build-and-push-backend'] # Explicitly wait for the build-and-push step to complete
images:
- 'gcr.io/gen-lang-client-0960260048/todo-backend:$_BUILD_ID' # Use $_BUILD_ID for final images list
options: # Added to specify logging behavior
  logging: CLOUD_LOGGING_ONLY # Directs logs to Cloud Logging
